name:                dansorder
version:             0.1.0.0
github:              "borisskert/dans-order"
license:             BSD3
author:              "Boris Skert"
maintainer:          "borisskert@gmail.com"
copyright:           "2022 Boris Skert"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/borisskert/dans-order#readme>

dependencies:
- base >= 4.7 && < 5
- split == 0.2.3.4
- json == 0.10.*

library:
  source-dirs: src

executables:
  dans-order-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dansorder

tests:
  dans-order-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dansorder
    - hspec == 2.7.10
